"""add_image_url_to_chat_files

Revision ID: efbae5d0ce1e
Revises: 018
Create Date: 2025-12-08 02:22:10.532414

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efbae5d0ce1e'
down_revision: Union[str, None] = '018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_robinhood_sessions_robinhood_username', table_name='robinhood_sessions')
    op.drop_index('ix_robinhood_sessions_session_id', table_name='robinhood_sessions')
    op.drop_table('robinhood_sessions')
    op.alter_column('brokerage_accounts', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index('idx_brokerage_accounts_broker', table_name='brokerage_accounts')
    op.drop_index('idx_brokerage_accounts_user_account', table_name='brokerage_accounts')
    op.create_index(op.f('ix_brokerage_accounts_id'), 'brokerage_accounts', ['id'], unique=False)
    op.add_column('chat_files', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('chat_files', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index('ix_chat_files_chat_filename', table_name='chat_files')
    op.drop_index('ix_chat_files_filename', table_name='chat_files')
    op.drop_index('idx_chat_messages_resource_id', table_name='chat_messages')
    op.drop_constraint('uq_chat_messages_chat_id_sequence', 'chat_messages', type_='unique')
    op.create_index(op.f('ix_chat_messages_resource_id'), 'chat_messages', ['resource_id'], unique=False)
    op.drop_constraint('chat_messages_resource_id_fkey', 'chat_messages', type_='foreignkey')
    op.drop_index('idx_unique_user_date', table_name='portfolio_snapshots')
    op.drop_index('idx_user_snapshots', table_name='portfolio_snapshots')
    op.create_index(op.f('ix_portfolio_snapshots_id'), 'portfolio_snapshots', ['id'], unique=False)
    op.alter_column('resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_resources_chat_id', table_name='resources')
    op.drop_index('idx_resources_created_at', table_name='resources')
    op.drop_index('idx_resources_user_id', table_name='resources')
    op.create_index(op.f('ix_resources_chat_id'), 'resources', ['chat_id'], unique=False)
    op.create_index(op.f('ix_resources_created_at'), 'resources', ['created_at'], unique=False)
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_user_id'), 'resources', ['user_id'], unique=False)
    op.alter_column('snaptrade_users', 'snaptrade_user_secret',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index('ix_snaptrade_users_session_id', table_name='snaptrade_users')
    op.create_index(op.f('ix_snaptrade_users_user_id'), 'snaptrade_users', ['user_id'], unique=False)
    op.drop_index('idx_symbol_analytics', table_name='trade_analytics')
    op.drop_index('idx_trade_analytics_data', table_name='trade_analytics', postgresql_using='gin')
    op.drop_index('idx_user_analytics', table_name='trade_analytics')
    op.create_index(op.f('ix_trade_analytics_id'), 'trade_analytics', ['id'], unique=False)
    op.drop_index('idx_user_sync_jobs', table_name='transaction_sync_jobs')
    op.create_index(op.f('ix_transaction_sync_jobs_id'), 'transaction_sync_jobs', ['id'], unique=False)
    op.drop_index('idx_external_id', table_name='transactions')
    op.drop_index('idx_symbol_transactions', table_name='transactions')
    op.drop_index('idx_transactions_data', table_name='transactions', postgresql_using='gin')
    op.drop_index('idx_user_symbol', table_name='transactions')
    op.drop_index('idx_user_transactions', table_name='transactions')
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.create_index('idx_user_transactions', 'transactions', ['user_id', sa.text('transaction_date DESC')], unique=False)
    op.create_index('idx_user_symbol', 'transactions', ['user_id', 'symbol'], unique=False)
    op.create_index('idx_transactions_data', 'transactions', ['data'], unique=False, postgresql_using='gin')
    op.create_index('idx_symbol_transactions', 'transactions', ['symbol', sa.text('transaction_date DESC')], unique=False)
    op.create_index('idx_external_id', 'transactions', ['user_id', 'external_id'], unique=False)
    op.drop_index(op.f('ix_transaction_sync_jobs_id'), table_name='transaction_sync_jobs')
    op.create_index('idx_user_sync_jobs', 'transaction_sync_jobs', ['user_id', sa.text('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_trade_analytics_id'), table_name='trade_analytics')
    op.create_index('idx_user_analytics', 'trade_analytics', ['user_id', sa.text('exit_date DESC')], unique=False)
    op.create_index('idx_trade_analytics_data', 'trade_analytics', ['data'], unique=False, postgresql_using='gin')
    op.create_index('idx_symbol_analytics', 'trade_analytics', ['symbol', sa.text('exit_date DESC')], unique=False)
    op.drop_index(op.f('ix_snaptrade_users_user_id'), table_name='snaptrade_users')
    op.create_index('ix_snaptrade_users_session_id', 'snaptrade_users', ['user_id'], unique=False)
    op.alter_column('snaptrade_users', 'snaptrade_user_secret',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_resources_user_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_created_at'), table_name='resources')
    op.drop_index(op.f('ix_resources_chat_id'), table_name='resources')
    op.create_index('idx_resources_user_id', 'resources', ['user_id'], unique=False)
    op.create_index('idx_resources_created_at', 'resources', ['created_at'], unique=False)
    op.create_index('idx_resources_chat_id', 'resources', ['chat_id'], unique=False)
    op.alter_column('resources', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_portfolio_snapshots_id'), table_name='portfolio_snapshots')
    op.create_index('idx_user_snapshots', 'portfolio_snapshots', ['user_id', sa.text('snapshot_date DESC')], unique=False)
    op.create_index('idx_unique_user_date', 'portfolio_snapshots', ['user_id', 'snapshot_date'], unique=False)
    op.create_foreign_key('chat_messages_resource_id_fkey', 'chat_messages', 'resources', ['resource_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_chat_messages_resource_id'), table_name='chat_messages')
    op.create_unique_constraint('uq_chat_messages_chat_id_sequence', 'chat_messages', ['chat_id', 'sequence'])
    op.create_index('idx_chat_messages_resource_id', 'chat_messages', ['resource_id'], unique=False)
    op.create_index('ix_chat_files_filename', 'chat_files', ['filename'], unique=False)
    op.create_index('ix_chat_files_chat_filename', 'chat_files', ['chat_id', 'filename'], unique=False)
    op.alter_column('chat_files', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('chat_files', 'image_url')
    op.drop_index(op.f('ix_brokerage_accounts_id'), table_name='brokerage_accounts')
    op.create_index('idx_brokerage_accounts_user_account', 'brokerage_accounts', ['user_id', 'account_id'], unique=False)
    op.create_index('idx_brokerage_accounts_broker', 'brokerage_accounts', ['broker_id'], unique=False)
    op.alter_column('brokerage_accounts', 'balance',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.create_table('robinhood_sessions',
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('encrypted_access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('encrypted_refresh_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('device_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logged_in', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_activity', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('robinhood_username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('session_id', name='robinhood_sessions_pkey')
    )
    op.create_index('ix_robinhood_sessions_session_id', 'robinhood_sessions', ['session_id'], unique=False)
    op.create_index('ix_robinhood_sessions_robinhood_username', 'robinhood_sessions', ['robinhood_username'], unique=False)
    # ### end Alembic commands ###

